baseURL = "https://fudolfo.xyz/"

defaultContentLanguage = 'es'
languageCode = "es-ar"

title = "Fudolfo"
theme = "ananke"
publishDir = "public"

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true

      

[taxonomies]
  tag = "tags"

[params]
  date_format = "02/01/2006"

[languages]
  [languages.es]
    languageName = "Espa√±ol"
    weight = 1