baseURL = "https://fudolfo.xyz/"
languageCode = "es-ar"
title = "Fudolfo"
theme = "ananke"
publishDir = "public"

[menu]

  [[menu.main]]
    name = "Sobre m√≠"
    url = "/about/"
    weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true

[taxonomies]
  tag = "tags"
  brainrot = "brainrots"